[build]
  command = "yarn build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/v1/dalle"
  to = "/.netlify/functions/dalle"
  status = 200
  force = true

[dev]
  command = "yarn dev"
  targetPort = 5173
  port = 8888
